apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: argocd-application-creator-gitlab
  title: Deploy New Application Manifests using GitLab
  description: Creates a new ArgoCD Application YAML based on shared infra values and helm chart for the application deployment passing the minimum required values. Opens a merge request in Gitlab.
  tags:
    - argocd
    - gitops
    - helm
spec:
  owner: unknown/guest
  type: gitops-config

  parameters:
    - title: Application Naming
      required: [bkst_app_name, bkst_app_stage, bkst_app_region]
      properties:
        bkst_app_name:
          title: New Application Name
          type: string
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
          maxLength: 16
          description: Unique name for the application (e.g., 'payroll-service').
          ui:help: "Hint: a lowercase name - must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character"
        bkst_app_stage:
          title: On which stage to deploy
          type: string
          description: Stage (e.g., 'dev' or 'staging' or 'prod').
        bkst_app_region:
          title: On which region will the app run
          type: string
          description: The cloud region (e.g., 'eu-west-2').

    - title: Container image and resources
      required: [bkst_app_imagename, bkst_app_image_tag, bkst_app_mem, bkst_app_cpu_limit]
      properties:
        bkst_app_imagereg:
          title: Container registry
          type: string
          description: The address of the container registry containing the image (e.g., 'docker.io/'). It should end with a "/" or it can be omitted if it's docker.io
        bkst_app_imagename:
          title: Container image name
          type: string
          description: The address of the container registry containing the image (e.g., 'myapp').
        bkst_app_image_tag:
          title: Container image tag
          type: string
          description: The tag of the container image (e.g., 'v1.0.0').
        bkst_app_health_probe:
          title: Health probe path
          type: string
          description: Health probe path (e.g., '/').
        bkst_app_mem:
          title: Memory requirements
          type: string
          description: How much memory to allow for the application as a maximum (e.g., '512Mi').
          pattern: '^[1-9][0-9]*(Mi|Gi)$'
        bkst_app_cpu_limit:
          title: CPU limit
          type: string
          description: How many CPU cores to limit the application as a maximum (e.g., '2').
          pattern: '^[0-9]+$'

  steps:
    - id: fetch-base
      name: Fetch and Render Template
      action: fetch:template
      input:
        url: ./skeleton/
        targetPath: ./helm/
        values:
          # Pass only the necessary variables to the templating engine
          bkst_app_name: ${{ parameters.bkst_app_name }}
          bkst_app_stage: ${{ parameters.bkst_app_stage }}
          bkst_app_region: ${{ parameters.bkst_app_region }}
          bkst_app_imagereg: ${{ parameters.bkst_app_imagereg }}
          bkst_app_imagename: ${{ parameters.bkst_app_imagename }}
          bkst_app_image_tag: ${{ parameters.bkst_app_image_tag }}
          bkst_app_health_probe: ${{ parameters.bkst_app_health_probe }}
          bkst_app_cpu_limit: ${{ parameters.bkst_app_cpu_limit }}
          bkst_app_mem: ${{ parameters.bkst_app_mem }}

    - id: rename-app-dir
      name: Rename the directories with the proper app name region and stage
      action: fs:rename
      input:
        files:
        # 1) deepest files FIRST (strip .hbs)
        - from: helm/APP_NAME/values/STAGE/REGION/values.yaml.hbs
          to: helm/APP_NAME/values/STAGE/REGION/values.yaml

        - from: helm/APP_NAME/values.yaml.hbs
          to: helm/APP_NAME/values.yaml

        - from: helm/APP_NAME/Chart.yaml.hbs
          to: helm/APP_NAME/Chart.yaml

        # 2) argocd application template (already outside APP_NAME)
        - from: helm/applications/templates/argocd-application-templ.yaml.hbs
          to: helm/applications/templates/application-${{ parameters.bkst_app_name }}.yaml

        # 3) REGION directory
        - from: helm/APP_NAME/values/STAGE/REGION
          to: helm/APP_NAME/values/STAGE/${{ parameters.bkst_app_region }}

        # 4) STAGE directory
        - from: helm/APP_NAME/values/STAGE
          to: helm/APP_NAME/values/${{ parameters.bkst_app_stage }}

        # 5) APP_NAME directory LAST
        - from: helm/APP_NAME
          to: helm/${{ parameters.bkst_app_name }}

    - id: create-merge-request
      name: Create Feature Branch and Merge Request
      action: publish:gitlab:merge-request
      input:
        repoUrl: 'gitlab.itgix.com?owner=${{ environment.secrets.repoOwner }}&repo=${{ environment.secrets.repoName }}'
        branchName: 'feat/new-app-${{ parameters.bkst_app_name }}'
        targetBranchName: 'main'
        title: 'New App: ${{ parameters.bkst_app_name }} Scaffolded'
        sourcePath: .
        description: 'This MR adds the initial configuration for the new application ${{ parameters.bkst_app_name }}.'

    - id: debug-mr-output
      name: Debug MR output
      action: debug:log
      input:
        message: ${{ steps['create-merge-request'].output | dump }}

  output:
    links:
      - title: Review the Merge Request and merge to apply changes
        url: ${{ steps['create-merge-request'].output.mergeRequestUrl }}
