apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: argocd-application-creator
  title: Create ArgoCD Application Manifest
  description: Creates a new ArgoCD Application YAML based on shared infra values.
  tags:
    - argocd
    - gitops
    - helm
spec:
  owner: unknown/guest
  type: gitops-config

  parameters:
    - title: Application Naming
      required: [bkst_app_name]
      properties:
        bkst_app_name:
          title: New Application Name
          type: string
          description: Unique name for the application (e.g., 'payroll-service').
    # Add other inputs here that you need to pass to the Scaffolder actions,
    # such as the GitOps repo URL, branch name, image etc.

  steps:
    - id: fetch-base
      name: Fetch and Render Template
      action: fetch:template
      input:
        url: ./skeleton
        # Assuming you put your ArgoCD manifest into a 'skeleton' folder
        targetPath: .
        values:
          # Pass only the necessary variables to the templating engine
          bkst_app_name: ${{ parameters.bkst_app_name }}

    - id: publish-manifest
      name: Publish to GitOps Repository
      action: publish:github # Replace with 'publish:github' or publish:gitlab if needed
      input:
        repoUrl: itgix/adp-demo-client-test.git # Replace with dynamic parameter
        #branch: new-app/${{ parameters.bkst_app_name }}
        sourcePath: . # Publish the generated file from the workspace
        #commitMessage: 'feat: Add ArgoCD Application for ${{ parameters.bkst_app_name }}'

    # STEP 2: Create a Pull Request (This pushes a new branch and opens the PR)
    - id: create-pull-request
      name: Create Feature Branch and Pull Request
      # This action is designed specifically for feature branching and PR creation
      action: publish:github:pull-request
      input:
        repoUrl: 'itgix/adp-demo-client-test.git'
        branchName: 'feat/new-app-${{ parameters.bkst_app_name }}'
        title: 'New App: ${{ parameters.bkst_app_name }} Scaffolded'
        gitCommitMessage: 'feat: Initial scaffold for ${{ parameters.bkst_app_name }}'
        sourcePath: .
        description: 'This PR adds the initial configuration for the new application.'

  output:
    links:
      - title: Go to Repository
    remoteUrl: ${{ steps['create-pull-request'].output.remoteUrl }}
